CREATE TABLE profiles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255),
    profile_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_profile UNIQUE (profile_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profiles (id);